title: My Own Private Thermopylae
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.thermopylae.net"
github_username:  leos

# Build settings
theme: minima
plugins:
  - jekyll-feed

